### PR TITLE
Try some slightly different background positioning

### PR DESCRIPTION
**Pull request by nein09**
Let's see if this does better on your phone.

### CODE REVIEW

**Comment by mishawilliams** [comment]
Better in landscape mode - I see both. In portrait mode, I see the house but not James. As your original comment seemed to indicate, James is prefered over the house. ;) 
screenshot_20190205-163218_chrome
screenshot_20190205-163234_chrome

**Comment by nein09** [comment]
That's even more interesting because it's doing exactly the opposite of what I would expect it to do in portrait mode.

Which browser are you using?

**Comment by mishawilliams** [comment]
Chrome - it's an Android.

I don't have an iPhone and it looks OK on my iPad in Safari.

**Comment by nein09** [comment]
I was afraid you were going to say that because when I try it in Chrome on my desktop, it does what I expect.

I'll have to look into this a little more.

**Pull request merged**
